import Head from "next/head";
import PageContainer from "components/PageContainer/PageContainer";
import Introduction from "components/Homepage/Introduction";
import CategorySection from "components/Homepage/CategorySection";
import styles from "styles/homepage.module.scss";
import { CATEGORIES_TYPE } from "utils";

export default function Homepage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageContainer>
        <Introduction />
        <div className={styles.wrapper}>
          <CategorySection categoryType={CATEGORIES_TYPE.recent} />
          <CategorySection categoryType={CATEGORIES_TYPE.tech} />
          <CategorySection categoryType={CATEGORIES_TYPE.wellbeing} />
        </div>
      </PageContainer>
    </>
  );
}
